//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlisverisOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsBasvurulari
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tel { get; set; }
        public string okul { get; set; }
        public string brans { get; set; }
        public string tc { get; set; }
        public Nullable<System.DateTime> basvuru { get; set; }
    }
}
