//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlisverisOtomasyonu.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class otomasyonEntities : DbContext
    {
        public otomasyonEntities()
            : base("name=otomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<eskiMusteri> eskiMusteri { get; set; }
        public virtual DbSet<EskiPersonel> EskiPersonel { get; set; }
        public virtual DbSet<IsBasvurulari> IsBasvurulari { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<Yetkili> Yetkili { get; set; }
    }
}
