//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlisverisOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int id { get; set; }
        public string M_Ad { get; set; }
        public string M_Soyad { get; set; }
        public string M_il { get; set; }
        public string M_ilce { get; set; }
        public string M_Tel { get; set; }
        public string M_Mail { get; set; }
        public string M_Adres { get; set; }
        public Nullable<System.DateTime> M_Tarih { get; set; }
    }
}
