//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlisverisOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkili
    {
        public int id { get; set; }
        public string Y_Ad { get; set; }
        public string Y_Soyad { get; set; }
        public string Y_TC { get; set; }
        public Nullable<System.DateTime> Y_DTarih { get; set; }
        public string Y_Sifre { get; set; }
        public string Y_Tel { get; set; }
        public Nullable<System.DateTime> Y_Tarih { get; set; }
    }
}
